export const ReminderTypes = {
  FETCH_REMINDERS_REQUEST: "FETCH_REMINDERS_REQUEST",
  FETCH_REMINDERS_SUCCESS: "FETCH_REMINDERS_SUCCESS",
  FETCH_REMINDERS_FAILURE: "FETCH_REMINDERS_FAILURE",
  ADD_REMINDER: "ADD_REMINDER",
  UPDATE_REMINDER: "UPDATE_REMINDER",
  DELETE_REMINDER: "DELETE_REMINDER",
  REMOVE_REMINDER: "REMOVE_REMINDER",
};
